-- AlterTable: User notification preferences + TA default location
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notifyAssist" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notifyClose" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notifyJoin" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notifyLeave" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultLocation" TEXT;

-- AlterTable: Queue office-hour session window
ALTER TABLE "Queue" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Queue" ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMP(3);
